#!/usr/bin/env python3
"""
Unit tests for ace_after_task.py - Learning Capture Logic (697 lines!)

CRITICAL: Tests filtering logic that prevents garbage learning.
Bug here = polluted playbook with ACE commands, greetings, trivial tasks.

Focus areas:
1. is_trivial_task() - Filters out garbage (56-111)
2. has_substantial_work_from_accumulated() - Quality gate (112-135)
3. summarize_tool_action/response() - Trajectory building (136-241)
"""

import sys
from pathlib import Path

# Add shared-hooks to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "plugins/ace/shared-hooks"))

from ace_after_task import is_trivial_task, has_substantial_work_from_accumulated, summarize_tool_action


# ============================================================================
# Test: is_trivial_task() - Garbage Filter
# ============================================================================

class TestTrivialTaskFilter:
    """
    CRITICAL: This filter prevents garbage from polluting the playbook.

    Bugs here mean learning from:
    - ACE commands themselves ("/ace-search", "ace-status")
    - Greetings ("hi", "hello", "thanks")
    - Simple queries ("what is X?", "show me Y")
    - Read-only commands ("git status", "ls", "cat")
    """

    def test_ace_slash_commands_are_trivial(self):
        """ACE slash commands should NOT trigger learning"""
        trivial = [
            "/ace-search 'test'",
            "/ace-status",
            "/ace-patterns",
            "/ace-learn",
            "/ace-configure",
            "/ace-bootstrap",
            "/ace-clear",
            "/ace-doctor",
            "ace:ace-search",
            "<command-message>ace-status</command-message>",
        ]

        for task in trivial:
            assert is_trivial_task(task), \
                f"ACE command '{task}' should be filtered as trivial"

    def test_greetings_are_trivial(self):
        """Greetings should NOT trigger learning"""
        greetings = [
            "hi",
            "hello",
            "hey",
            "thanks",
            "thank you",
            "ok",
            "okay",
            "yes",
            "no",
            "sure",
        ]

        for greeting in greetings:
            assert is_trivial_task(greeting), \
                f"Greeting '{greeting}' should be filtered as trivial"

    def test_simple_queries_are_trivial(self):
        """Simple questions should NOT trigger learning"""
        queries = [
            "what is authentication?",
            "how do I implement caching?",
            "why did this fail?",
            "where is the config file?",
            "can you show me the code?",
            "could you explain this?",
            "list all files",
            "show me the logs",
            "display the error",
            "check status",
        ]

        for query in queries:
            assert is_trivial_task(query), \
                f"Query '{query}' should be filtered as trivial"

    def test_read_only_commands_are_trivial(self):
        """Read-only git/file commands should NOT trigger learning"""
        readonly = [
            "git status",
            "git log",
            "git diff",
            "git branch",
            "git show",
            "ls -la",
            "cat file.txt",
            "head -n 10 log.txt",
            "tail -f output.log",
        ]

        for cmd in readonly:
            assert is_trivial_task(cmd), \
                f"Read-only command '{cmd}' should be filtered as trivial"

    def test_system_messages_are_trivial(self):
        """System-generated messages should NOT trigger learning"""
        system_msgs = [
            "caveat: messages below were generated by user",
            "compact",
            "/compact",
        ]

        for msg in system_msgs:
            assert is_trivial_task(msg), \
                f"System message '{msg}' should be filtered as trivial"

    def test_actual_work_is_not_trivial(self):
        """Real implementation tasks should trigger learning"""
        real_work = [
            "Implement user authentication with JWT",
            "Add caching layer using Redis",
            "Fix the bug in payment processing",
            "Refactor the database access layer",
            "Write tests for the API endpoints",
            "Update the deployment pipeline",
        ]

        for task in real_work:
            assert not is_trivial_task(task), \
                f"Real work '{task}' should NOT be filtered"

    def test_REGRESSION_multiline_tasks_handled(self):
        """Multiline task descriptions should be handled correctly"""
        multiline = """Implement authentication flow:
1. Add login endpoint
2. Create JWT tokens
3. Validate on protected routes"""

        # Should NOT be trivial (contains real work)
        assert not is_trivial_task(multiline), \
            "Multiline tasks with implementation should not be filtered"

    def test_REGRESSION_case_insensitive_patterns(self):
        """Pattern matching should handle case variations"""
        # Currently patterns are case-sensitive (lowercase only)
        # This might be a bug - test current behavior
        assert is_trivial_task("hello"), "Lowercase greeting"
        # Uppercase NOT filtered (potential bug?)
        assert not is_trivial_task("HELLO"), "Uppercase greeting not filtered (case-sensitive bug?)"


# ============================================================================
# Test: has_substantial_work_from_accumulated() - Quality Gate
# ============================================================================

class TestSubstantialWorkGate:
    """
    Quality gate: Only learn if substantial work was done.

    Prevents learning from:
    - Single file read ("Read file.txt")
    - Simple git status check
    - Quick grep search

    Requires multiple substantive tool uses.
    """

    def test_single_read_not_substantial(self):
        """Single Read is not substantial work"""
        tools = [
            {"tool_name": "Read", "tool_input": {"file_path": "/test/file.txt"}}
        ]

        assert not has_substantial_work_from_accumulated(tools), \
            "Single Read should not be substantial"

    def test_single_bash_not_substantial(self):
        """Single Bash command is not substantial work"""
        tools = [
            {"tool_name": "Bash", "tool_input": {"command": "git status"}}
        ]

        assert not has_substantial_work_from_accumulated(tools), \
            "Single Bash should not be substantial"

    def test_single_grep_not_substantial(self):
        """Single Grep is not substantial work"""
        tools = [
            {"tool_name": "Grep", "tool_input": {"pattern": "TODO"}}
        ]

        assert not has_substantial_work_from_accumulated(tools), \
            "Single Grep should not be substantial"

    def test_write_is_substantial(self):
        """Write/Edit operations ARE substantial work"""
        tools = [
            {"tool_name": "Write", "tool_input": {"file_path": "/test/new_file.py", "content": "code"}}
        ]

        assert has_substantial_work_from_accumulated(tools), \
            "Write should be substantial work"

    def test_edit_is_substantial(self):
        """Edit operations ARE substantial work"""
        tools = [
            {"tool_name": "Edit", "tool_input": {"file_path": "/test/file.py", "old_string": "foo", "new_string": "bar"}}
        ]

        assert has_substantial_work_from_accumulated(tools), \
            "Edit should be substantial work"

    def test_multiple_reads_is_substantial(self):
        """Multiple Read operations (>2) ARE substantial work"""
        tools = [
            {"tool_name": "Read", "tool_input": {"file_path": "/test/file1.py"}},
            {"tool_name": "Read", "tool_input": {"file_path": "/test/file2.py"}},
            {"tool_name": "Read", "tool_input": {"file_path": "/test/file3.py"}},
        ]

        assert has_substantial_work_from_accumulated(tools), \
            "Multiple Reads should be substantial work"

    def test_read_plus_edit_is_substantial(self):
        """Read followed by Edit IS substantial work"""
        tools = [
            {"tool_name": "Read", "tool_input": {"file_path": "/test/file.py"}},
            {"tool_name": "Edit", "tool_input": {"file_path": "/test/file.py", "old_string": "foo", "new_string": "bar"}},
        ]

        assert has_substantial_work_from_accumulated(tools), \
            "Read+Edit should be substantial work"

    def test_empty_tools_not_substantial(self):
        """Empty tool list is not substantial"""
        assert not has_substantial_work_from_accumulated([]), \
            "Empty tools should not be substantial"


# ============================================================================
# Test: summarize_tool_action() - Trajectory Building
# ============================================================================

class TestToolSummarization:
    """
    Tests trajectory building logic.

    Per ACE Research Paper: Trajectory should contain:
    - Tool actions (inputs)
    - Tool responses (outputs)
    - Execution feedback (success/failure)
    """

    def test_read_tool_summarized(self):
        """Read tool should show file path"""
        summary = summarize_tool_action("Read", {"file_path": "/src/auth.py"})

        assert "auth.py" in summary, "Summary should include filename"

    def test_write_tool_summarized(self):
        """Write tool should show file path and size"""
        summary = summarize_tool_action("Write", {
            "file_path": "/src/new_file.py",
            "content": "def foo():\n    pass\n"
        })

        assert "new_file.py" in summary, "Summary should include filename"
        assert "27 chars" in summary or "bytes" in summary.lower(), "Summary should include size"

    def test_edit_tool_summarized(self):
        """Edit tool should show file path and change"""
        summary = summarize_tool_action("Edit", {
            "file_path": "/src/config.py",
            "old_string": "DEBUG = False",
            "new_string": "DEBUG = True"
        })

        assert "config.py" in summary, "Summary should include filename"
        assert "DEBUG = False" in summary or "old" in summary.lower(), "Summary should reference change"

    def test_bash_tool_summarized(self):
        """Bash tool should show command"""
        summary = summarize_tool_action("Bash", {"command": "npm install"})

        assert "npm install" in summary, "Summary should include command"

    def test_grep_tool_summarized(self):
        """Grep tool should show pattern"""
        summary = summarize_tool_action("Grep", {"pattern": "TODO", "path": "/src"})

        assert "TODO" in summary, "Summary should include pattern"

    def test_unknown_tool_handled(self):
        """Unknown tools should be handled gracefully"""
        summary = summarize_tool_action("UnknownTool", {"foo": "bar"})

        assert "UnknownTool" in summary, "Summary should include tool name"
        # Should not crash, should return something useful
        assert isinstance(summary, str), "Summary should be a string"
        assert len(summary) > 0, "Summary should not be empty"


# Run a quick sanity check
if __name__ == "__main__":
    print("Testing is_trivial_task()...")
    assert is_trivial_task("/ace-search 'test'"), "ACE commands should be trivial"
    assert is_trivial_task("hello"), "Greetings should be trivial"
    assert not is_trivial_task("Implement authentication"), "Real work should not be trivial"
    print("✓ Basic tests pass!")

    print("\nTesting has_substantial_work_from_accumulated()...")
    assert not has_substantial_work_from_accumulated([{"tool_name": "Read", "tool_input": {}}]), "Single read not substantial"
    assert has_substantial_work_from_accumulated([{"tool_name": "Write", "tool_input": {}}]), "Write is substantial"
    print("✓ Quality gate tests pass!")

    print("\nTesting summarize_tool_action()...")
    summary = summarize_tool_action("Read", {"file_path": "/test.py"})
    assert "test.py" in summary, "Summary should include filename"
    print("✓ Summarization tests pass!")

    print("\n✅ All sanity checks passed!")
